[package]
name = "idash-sgx-nn"
version = "0.1.0"
authors = ["Natnatee Dokmai <ndokmai@indiana.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.12"
ndarray-parallel = "0.9.0"
byteorder = "1.3.2"
